runtime: python311
# entrypoint: uwsgi --http-socket :$PORT --wsgi-file main.py --callable app --master --processes 1 --threads 2
# manual_scaling:
#   instances: 1

# handlers:
#   - url: /.*
#     script: server.py

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
  # - url: /static
  #   static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
  - url: /.*
    script: auto
